// data.js
// Dados brutos do currículo. Edite textos, experiências, competências e idiomas aqui.

export const data = {
				pt: {
					name: "Marcelo Vianna Pacheco",
					title: "Instrutor de Educação Física | Almoxarife | Coordenador de Materiais",
					summary:
						"Sou profissional de Educação Física com forte experiência como instrutor de Ed. Física offshore onde atuei em um flotel de última geração. Antes disto, como possuo formação técnica em mecânica industrial e inglês fluente, desenvolvi vasta experiência e vivência offshore nacional e internacional atuando como almoxarife em diversos tipos de embarcações ao longo de mais de 8 anos.",
					summaryTitle: "Resumo Profissional",
					educationTitle: "Formação Acadêmica",
					edu1: "Bacharelado em Educação Física (2005–2008)",
					edu2: "Técnico em Mecânica Industrial (2009–2010)",
					skillsTitle: "Competências",
					skills: [
						"Almoxarifado Offshore",
						"Gestão de Inventário",
						"Logística",
						"TEROMARINE TM v2",
						"AMOS Business Suite",
						"Planejamento de Materiais",
						"Controle de Estoque",
					],
					languagesTitle: "Idiomas",
					languages: ["Português — Nativo", "English — Fluent"],
					experienceTitle: "Experiência Profissional",
					experiences: [
						{
							company: "Prosafe",
							role: "Instrutor de Ed. Física Offshore",
							period: "Ago 2019 – Dez 2022",
							location: "Flotel Safe Eurus",
							desc: "Atuei como Instrutor de Academia (GYM Instructor). Gerenciei as operações da academia a bordo e desenvolvi programas de treinamento físico para tripulações multinacionais, com foco na prevenção de lesões e na manutenção da saúde.",
						},
            {
							company: "Empresarial Consultoria LTDA",
							role: "Almoxarife Offshore",
							period: "Fev 2019 – Ago 2019",
							location: "Petrobras FPSO P-77",
							desc: "Em minha função, gerencio e supervisiono o controle de materiais do almoxarifado. Utilizei o SAP R/3 para a gestão de inventário e controle de estoque em todas as unidades *offshore* da Petrobras. Isso inclui a organização, a verificação e a manutenção de todos os materiais que entram e saem da plataforma.",
						},
						{
							company: "Subsea7",
							role: "Almoxarife Offshore / Coordenador de Materiais",
							period: "Jul 2015 – Out 2017",
							location: "PLSV Seven Rio",
							desc: "Fui responsável pela coordenação das operações de inventário e planejamento da estrutura do Almoxarifado utilizando o sistema TEROMARINE – TM v2.",
						},
						{
							company: "BlueOOS / OOS International",
							role: "Almoxarife Offshore / Coordenador de Materiais",
							period: "Abr 2014 – Nov 2014",
							location: "Flotel Prometheus",
							desc: "Atuei como Coordenador e Gerente de Almoxarifado, supervisionando as operações, o planejamento estrutural e o gerenciamento das solicitações de materiais a bordo.",
						},
						{
							company: "Atlantica Management (USA) Inc.",
							role: "Coordenador de Materiais Offshore",
							period: "Jun 2012 – Abr 2014",
							location: "Plataforma de Perfuração (China/Brasil)",
							desc: "Trabalhei no projeto desde a fase inicial de desenvolvimento na China, supervisionando todos os materiais e operações de almoxarifado.",
						},
						{
							company: "MODEC",
							role: "Almoxarife Offshore",
							period: "Fev 2012 – Mai 2012",
							location: "FPSO Cidade de Santos",
							desc: "Fui responsável pelo controle de estoque, criação e gestão de solicitações de materiais a bordo utilizando AMOS Business Suite 9.",
						},
						{
							company: "McDermott International",
							role: "Operador de Rádio Offshore",
							period: "Ago 2011 – Out 2012",
							location: "PLSV Ágil",
							desc: "Prestei serviços de apoio operacional a aeronaves e coordenação administrativa offshore.",
						},
						{
							company: "Queiroz Galvão Óleo e Gás",
							role: "Almoxarife Assistente Offshore",
							period: "Jan 2011 – Mar 2011",
							location: "Plataforma Laguna Star",
							desc: "Participei de todo o processo de descarregamento e realizei inventário completo de mais de 8.000 itens.",
						},
						{
							company: "Wellstream",
							role: "Almoxarife Assistente",
							period: "Jul 2010",
							location: "Navio Aker Wayfare (Niterói)",
							desc: "Fui responsável pelo controle de estoque e distribuição de EPIs e materiais operacionais.",
						},
						{
							company: "Força Aérea Brasileira (FAB)",
							role: "Soldado",
							period: "Jan 2004 – Dez 2008",
							location: "Base Militar do Galeão",
							desc: "Atuei no Pelotão de Infantaria e prestei suporte administrativo e técnico em Tecnologia da Informação.",
						},
					],
				},
				en: {
					name: "Marcelo Vianna Pacheco",
					title: "Gym Teacher | Storekeeper | Logistics & Planning | Offshore",
					summary:
						"I am a Physical Education professional with extensive experience as an offshore GYM Instructor, having worked on a last-generation flotel. Before this, with a technical background in industrial mechanics and fluent English, I developed vast experience in the offshore sector.",
					summaryTitle: "Professional Summary",
					educationTitle: "Education",
					edu1: "Bachelor's Degree in Physical Education (2005–2008)",
					edu2: "Technical Degree in Industrial Mechanics (2009–2010)",
					skillsTitle: "Skills",
					skills: [
						"Gym Teacher",
						"Physical Education",
						"Offshore Warehouse",
						"Inventory Management",
						"Logistics",
						"Materials Planning",
						"Stock Control",
					],
					languagesTitle: "Languages",
					languages: ["Portuguese — Native", "English — Fluent"],
					experienceTitle: "Professional Experience",
					experiences: [
						{
							company: "Prosafe",
							role: "Offshore Physical Education Instructor",
							period: "Aug 2019 – Dec 2022",
							location: "Flotel Safe Eurus",
							desc: "I managed the onboard gym operations and developed physical training programs for multinational crews, focusing on injury prevention and health maintenance.",
						},
						{
							company: "Empresarial Consultoria LTDA",
							role: "Storekeeper Offshore",
							period: "Feb 2019 – Aug 2019",
							location: "Petrobras FPSO P-77",
							desc: "In my role, I manage and oversee the control of warehouse materials. I utilize SAP R/3 for inventory management and stock control across all Petrobras offshore units. This includes the organization, verification, and maintenance of all materials entering and leaving the platform.",
						},
						{
							company: "Subsea7",
							role: "Offshore Storekeeper / Materials Coordinator",
							period: "July 2015 – Oct 2017",
							location: "PLSV Seven Rio",
							desc: "I coordinated inventory operations and warehouse structure planning using the TEROMARINE – TM v2 system.",
						},
						{
							company: "BlueOOS / OOS International",
							role: "Offshore Warehouse Clerk / Materials Coordinator",
							period: "Apr 2014 – Nov 2014",
							location: "Flotel Prometheus",
							desc: "I acted as Warehouse Coordinator and Manager, supervising operations and material requests onboard.",
						},
						{
							company: "Atlantica Management (USA) Inc.",
							role: "Materials Coordinator",
							period: "Jun 2012 – Apr 2014",
							location: "Drilling Platform (China/Brazil)",
							desc: "I worked from the initial development phase in China, overseeing all materials and warehouse operations.",
						},
						{
							company: "MODEC",
							role: "Offshore Warehouse",
							period: "Feb 2012 – May 2012",
							location: "FPSO Cidade de Santos",
							desc: "I was responsible for inventory control and material requests using AMOS Business Suite 9.",
						},
						{
							company: "McDermott International",
							role: "Offshore Radio Operator",
							period: "Aug 2011 – Oct 2012",
							location: "PLSV Ágil",
							desc: "I provided operational support to aircraft and offshore administrative coordination.",
						},
						{
							company: "Queiroz Galvão Oil and Gas",
							role: "Offshore Assistant Storekeeper",
							period: "Jan 2011 – Mar 2011",
							location: "Laguna Star Platform",
							desc: "",
						},
						{
							company: "Wellstream",
							role: "Assistant Storekeeper",
							period: "Jul 2010",
							location: "Aker Wayfare Ship (Niterói)",
							desc: "I was responsible for inventory control and distribution of PPE and operational materials.",
						},
						{
							company: "Brazilian Air Force (FAB)",
							role: "Soldier",
							period: "Jan 2004 – Dec 2008",
							location: "Galeão Military Base",
							desc: "I served in the Infantry Platoon and provided administrative and technical IT support.",
						},
					],
				},
			}
