// data.js
// Dados brutos do currículo. Edite textos, experiências, competências e idiomas aqui.

export const data = {
	pt: {
		name: "Marcelo Vianna Pacheco",
		title: "Profissional de Educação Física | Gym Teacher Offshore | Gestão de Fitness e Academias | Storekeeper | Gestão de Materiais e Estoques | Operações Offshore",
		summary: "Profissional de Operações Offshore, Logística, Gestão de Materiais e Educação Física, com mais de 10 anos de experiência em ambientes offshore nacionais e internacionais de alta exigência. Minha trajetória profissional combina operações offshore, gestão de materiais e estoques, suporte logístico, gestão de academias, treinamento físico e Educação Física, proporcionando uma visão versátil tanto de ambientes operacionais quanto de gestão e desenvolvimento de pessoas.",
		summaryTitle: "Resumo Profissional",
		educationTitle: "Formação Acadêmica",
		edu1: "Bacharelado em Educação Física (2005–2008)",
		edu2: "Técnico em Mecânica Industrial (2009–2010)",
		skillsTitle: "Competências",
		skills: [
      "Educação Fisica",
      "Instrutor de Academia",
			"Almoxarifado Offshore",
			"Gestão de Inventário",
			"Logística",
			"Planejamento de Materiais",
			"Controle de Estoque",
		],
		languagesTitle: "Idiomas",
		languages: ["Português — Nativo", "English — Fluent"],
		experienceTitle: "Experiência Profissional",
		experiences: [
      {
				company: "Autonomo",
				role: "Desenvolvedor de Software Junior",
				period: "Out 2023 – Fev 2026",
				location: "Cabo Frio - RJ, Brasil",
				desc: "Fora do mercado offshore, dediquei-me a desenvolver habilidades em criação de sites. Nesse período, também cofundei uma pequena *startup* com dois amigos, oferecendo nossas competências e serviços a pequenas empresas."
			},
			{
				company: "Prosafe",
				role: "Instrutor de Educação Física Offshore",
				period: "Out 2019 – Dez 2021",
				location: "Flotel Safe Eurus",
				desc: "Responsável pela Academia a Bordo. Gerenciei as operações da academia da embarcação e desenvolvi programas de treinamento físico para tripulações multinacionais, com foco na prevenção de lesões e manutenção da saúde. Fui responsável por toda a atividade física, organização e cuidados com o ambiente da academia."
			},
			{
				company: "Empresarial Consultoria LTDA",
				role: "Almoxarife Offshore",
				period: "Set 2019 – Out 2019",
				location: "Petrobras FPSO P-77",
				desc: "Responsável pela integração da equipe de almoxarifado, gerenciando todo o inventário, logística, embarque e desembarque de materiais da plataforma. Atuei diretamente com o time de movimentação de cargas otimizando o fluxo e o tempo das operações. Realizei melhorias na organização de contêineres e equipamentos a bordo (contratados e da Petrobras). Utilizei o sistema SAP para gestão e controle de estoque.",
			},
			{
				company: "Subsea7",
				role: "Almoxarife Offshore / Coordenador de Materiais",
				period: "Jul 2015 – Out 2017",
				location: "PLSVs Seven Rio, Seven Mar e Seven Waves",
				desc: "Responsável pelo Inventário e Logística de Materiais. Gerenciei todo o inventário e logística de materiais da embarcação, com foco principal no suporte às equipes de convés durante operações de lançamento de linhas. Atuei diretamente na supervisão e fornecimento de equipamentos e materiais para operações de pull-in.",
			},
			{
				company: "OOS International",
				role: "Almoxarife Offshore / Coordenador de Materiais",
				period: "Mai 2014 – Nov 2014",
				location: "Embarcação de Acomodação (Flotel) – Prometheus",
				desc: "Contrato Temporário ATLAS PROFESSIONALS DO BRASIL LTDA - Responsável pela supervisão das operações de almoxarifado, planejamento do layout estrutural e gerenciamento de solicitações de materiais a bordo. Coordenei o controle de estoque, manuseio de manifestos logísticos e processos de carregamento/descarregamento. Foquei na eficiência operacional, rastreabilidade, organização e suporte contínuo ao abastecimento em ambientes offshore."
			},
			{
				company: "Atlantica Management (USA) Inc.",
				role: "Coordenador de Materiais Offshore",
				period: "Jun 2013 – Abr 2014",
				location: "Plataforma de Perfuração para Licitação (China/Brasil)",
				desc: "Atuei desde a fase inicial de desenvolvimento na China, supervisionando materiais e operações de almoxarifado na preparação da plataforma. Gerenciei o planejamento do layout, organização do estoque e estruturação operacional para garantir prontidão para implantação no Brasil.\n\nDurante 3 meses, na etapa de preparativos finais no Porto Offshore Triunfo Logística (Almoxarifado 7 - Rio de Janeiro), coordenei logística portuária e materiais. A bordo, utilizei os sistemas AMOS Business Suite 2 e SAP para gerenciar solicitações, inventários e operações logísticas, estruturando fluxos de trabalho que garantiram rastreabilidade, organização e suporte operacional eficiente em ambiente offshore.",
			},
			{
				company: "MODEC",
				role: "Almoxarife Assistente Offshore",
				period: "Fev 2013 – Mai 2013",
				location: "FPSO Cidade de Santos",
				desc: "Contrato temporário G-COMEX ÓLEO & GÁS LTDA - Atuei como almoxarife assistente (Suporte) e pude ajudar na revisão do inventário da embarcação, na reorganização dos materiais no espaço físico do almoxarifado e no suporte direto ao almoxarife sênior nas rotinas e desafios constantes e diários.",
			},
			{
				company: "McDermott International",
				role: "Almoxarife Assistente Offshore",
				period: "Set 2012 – Dez 2012",
				location: "Embarcação AGILE PLSV",
				desc: "Contrato temporário G-COMEX ÓLEO & GÁS LTDA - Assistente de almoxarifado (Suporte) e pude ajudar no inventário da embarcação e aprender muito sobre lançamento de linhas (Pull-In). Fui responsável por fornecer equipamentos e materiais ligados aos principais projetos do navio, atuando diretamente com o time de Lancamento de Linhas (Time de Operações de Pull-In).",
			},
			{
				company: "Queiroz Galvão Óleo e Gás",
				role: "Almoxarife Assistente Offshore",
				period: "Mai 2012 – Ago 2012",
				location: "Navio-sonda Laguna Star",
				desc: "Contrato temporário G-COMEX ÓLEO & GÁS LTDA - Participei da viagem de Singapura ao Brasil (75 dias), atuando como Assistente de Almoxarife. Fui responsável pelo descarregamento, estruturação completa do almoxarifado e inventário de mais de 8.000 itens.\n\nPrincipais resultados:\n• Economia real de 75% em tempo e custos logísticos na chegada ao Brasil;\n• Eliminação da necessidade de contratar empresa externa para revisão e manutenção do inventário;\n• Economia de milhares de dólares e redução significativa de tempo logístico para os departamentos da Queiroz.",
			},
			{
				company: "Web Sigma Agencia Digital",
				role: "UX/UI Developer",
				period: "Jan 2010 - Ago 2011",
				location: "Araruama - RJ, Brasil",
				desc: "Trabalhei como UX/UI Designer. Fui responsável pelo desenvolvimento da interface e da usabilidade de diversos projetos para clientes de médio e grande porte de variados setores, como supermercados, beleza e estética, e varejo, entre outros.",
			},
			{
				company: "Força Aérea Brasileira (FAB)",
				role: "Soldado",
				period: "Jan 2004 – Dez 2008",
				location: "Base Militar do Galeão",
				desc: "Servi como Soldado de Segunda Classe no Exército Brasileiro, atuando no Pelotão de Infantaria e apoiando atividades operacionais militares, rotinas disciplinares e procedimentos de segurança. Também trabalhei no setor de Tecnologia da Informação do Parque de Equipamentos Militares, prestando suporte administrativo e técnico para sistemas operacionais e processos internos.",
			},
		],
	},
	en: {
		name: "Marcelo Vianna Pacheco",
		title: "Physical Education Professional | Offshore Gym Teacher | Fitness & Gym Operations | Storekeeper | Materials & Inventory Management | Offshore Operations",
		summary: "Offshore Operations, Logistics, Materials Management, and Physical Education professional with more than 10 years of experience working in demanding national and international offshore environments. My professional background combines offshore operations, materials and inventory management, logistics support, fitness operations, and physical education, giving me a versatile perspective across both operational and people-focused environments.",
		summaryTitle: "Professional Summary",
		educationTitle: "Education",
		edu1: "Bachelor's Degree in Physical Education (2005–2008)",
		edu2: "Technical Degree in Industrial Mechanics (2009–2010)",
		skillsTitle: "Skills",
		skills: [
			"Gym Teacher",
			"Physical Education",
			"Offshore Warehouse",
			"Inventory Management",
			"Logistics",
			"Materials Planning",
			"Stock Control",
		],
		languagesTitle: "Languages",
		languages: ["Portuguese — Native", "English — Fluent"],
		experienceTitle: "Professional Experience",
		experiences: [
      {
        company: "Self Employed",
				role: "Junior Software Engineer",
				period: "Oct 2023 – Feb 2026",
				location: "Cabo Frio - RJ, Brazil",
				desc: "Outside the offshore market, I spent time studying website development skills. During this period, I also co-founded a small startup with two friends, bringing our skills and services to small businesses."
      },
			{
				company: "Prosafe",
				role: "Offshore Gym Teacher",
				period: "Oct 2019 – Dec 2021",
				location: "UMS Safe Eurus",
				desc: "Responsible for the overall management of the onboard gym, ensuring the organization, availability, and safe use of fitness equipment and facilities. Supervised and supported more than 500 offshore professionals who used the gym daily, guiding proper training practices, correct exercise execution, and the appropriate use of fitness equipment. Focused on promoting safety during physical activities, preventing injuries and musculoskeletal trauma, and minimizing risks associated with improper exercise techniques or incorrect equipment use. I also contributed to the health, well-being, and quality of life of offshore personnel by applying knowledge of Physical Education, fitness training, and injury prevention in an offshore environment.",
			},
			{
				company: "Empresarial Consultoria LTDA",
				role: "Storekeeper Offshore",
				period: "Sep 2019 – Oct 2019",
				location: "Petrobras FPSO P-77",
				desc: "Temporary contract EMPRESARIAL ASSESSORIA EM GESTÃO E SAÚDE LTDA - I worked as an offshore support warehouseman, joining the team responsible for managing the entire inventory, logistics, and the loading and unloading of materials for the P-77 platform. My role involved direct collaboration with the cargo handling team to optimize time and enhance the efficiency of cargo operations. I was also responsible for organizing containers and all onboard equipment, including both contractor-owned and Petrobras-owned items. Additionally, I utilized the SAP system for inventory management and control.",
			},
			{
				company: "Subsea7",
				role: "Offshore Operational Storekeeper",
				period: "July 2015 – Oct 2017",
				location: "PLSV Seven Rio / Seven Mar and Seven Waves",
				desc: "Responsible for the vessel's entire inventory and materials logistics, and most importantly, providing support to deck teams for line-laying operations, working directly to oversee and supply equipment and materials related to pull-in operations.",
			},
			{
				company: "BlueOOS / OOS International",
				role: "Offshore Storekeeper / Materials Coordinator",
				period: "May 2014 – Nov 2014",
				location: "Accommodation Vessel Flotel - Prometheus",
				desc: "Temporary Contract ATLAS PROFESSIONALS DO BRASIL LTDA - As a Warehouse Coordinator and Warehouse Manager, I am responsible for overseeing warehouse operations, planning the structural layout, and managing onboard material requests. I gained experience in coordinating inventory control processes and handling logistics manifests for both loading and offloading operations. My focus was on ensuring operational efficiency, traceability, organization, and continuous supply support in offshore environments.",
			},
			{
				company: "Atlantica Management (USA) Inc.",
				role: "Offshore Storekeeper / Materials Coordinator",
				period: "Jun 2013 – Apr 2014",
				location: "China (Dalian) / Triunfo Logística – RJ, Brazil",
				desc: "Worked on the project from its early development phase in China (Dalian Shipyard), being responsible for all material and warehouse operations during the platform preparation process. Managed warehouse layout planning, inventory organization, and operational structuring to support the platform’s readiness for deployment to Brazil. Supply Chain Optimizations and also gained hands-on experience with port logistics and material coordination during the platform’s 3-month operational stay at Warehouse 7, located at Triunfo Logística Offshore Port – Rio de Janeiro, Brazil.",
			},
			{
				company: "MODEC",
				role: "Offshore Assistant Storekeeper",
				period: "Feb 2013 – May 2013",
				location: "FPSO Cidade de Santos",
				desc: "Temporary contract G-COMEX OLEO & GAS LTDA - I worked as an assistant storekeeper (Support), helping to review the vessel's inventory, reorganize materials within the storeroom, and provide direct support to the senior storekeeper with daily routines and ongoing challenges.",
			},
			{
				company: "McDermott International, Ltd",
				role: "Offshore Assistant Storekeeper",
				period: "Sep 2012 – Dec 2012",
				location: "PLSV Agile",
				desc: "Temporary contract G-COMEX OLEO & GAS LTDA - I worked on a temporary contract as a warehouse assistant (support role), where I assisted with vessel inventory and gained extensive knowledge of line installation (pull-in) operations. I was responsible for supplying equipment and materials for the vessel's key projects, working directly with the line installation team (Pull-In Operations Team).",
			},
			{
				company: "Queiroz Galvão Oil and Gas",
				role: "Offshore Assistant Storekeeper",
				period: "May 2012 - Aug 2012",
				location: "Drilling Vessel - Laguna Star",
				desc: "Temporary contract G-COMEX OLEO & GAS LTDA - I participated in the trip of the drilling vessel that departed from Singapore to Brazil, which lasted 75 days. I worked as a storekeeper assistant and was involved in the entire unloading process and inventory. This culminated in preparations for Brazil, during which we conducted a complete inventory of over 8,000 items. I closely monitored all stages of the physical and operational setup of the warehouse. As a result of our efforts, the company achieved a 35% advantage in terms of time and cost savings on average. The real result was a 75% advantage for the company in terms of both time and cost savings when arriving in Brazil for logistics departments. Thanks to the 75-day voyage warehouse team's efforts, Queiroz was able to focus its logistics elsewhere. We also reduced the need to hire a new company to handle the inventory review and maintenance. Thousands of dollars were saved, and a significant amount of unnecessary logistical time was eliminated.",
			},
			{
				company: "Web Sigma",
				role: "UX/UI Developer",
				period: "Jan 2010 - Aug 2011",
				location: "Araruama - Rio de Janeiro",
				desc: "I worked as a UX/UI Designer. I was responsible for developing the interface and usability for various projects for medium- and large-scale clients across diverse sectors, such as supermarkets, beauty and aesthetics, and retail, among others.",
			},
			{
				company: "Brazilian Air Force (FAB)",
				role: "Soldier",
				period: "Jan 2004 – Dec 2008",
				location: "Galeão Military Base",
				desc: "I served in the Infantry Platoon and provided administrative and technical IT support.",
			},
		],
	},
};
